# Use Node.js 22 Alpine as the base image
FROM node:22-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Install nodemon globally for auto-reloading
RUN npm install -g nodemon

# Expose the port
EXPOSE 3001
# Use Nodemon for live reloading
CMD ["npm", "run", "start:dev"]
