services:
  ddd-ecommerce-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name:
      ddd-ecommerce-app
    env_file:
      - .env.dev 
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - ddd-ecommerce-db
      - ddd-ecommerce-redis
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped


  ddd-ecommerce-db:
    image: postgres:16-alpine
    container_name:
      ddd-ecommerce-db
    env_file:
      - .env.dev 
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
  ddd-ecommerce-redis:
    image: redis:7.4-alpine
    container_name:
      ddd-ecommerce-redis
    env_file:
      - .env.dev
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redisdata:/data 
    command: ["redis-server", "--appendonly", "yes"]
  
volumes:
  pgdata:
  redisdata:
